### ISSUE TITLE
Join Bioconda

### ISSUE THREAD

**Issue by johanneskoester** [compbiocore/conda-recipes#3]
Dear compbiocore team,
I have just seen your efforts to build conda packages for bioinformatics. Maybe you haven't seen this yet, but there is a huge community project to do this: https://bioconda.github.io.
We are over 200 developers and already provide over 3000 conda packages. Maybe you are interested to join us?

Best,
Johannes

**Comment by ashokrags** [comment]
Hi Johannes,
      Thanks for reaching out to us. We are very grateful to the bioconda team  to have setup this excellent resource and we are definitely engaged in contributing to bioconda from our end. In fact,   I met Ryan Dale at the Genome Informatics conference and had asked him to push a recipe for the `subread` package that was created as part of this repo.
     Our long-term goal is to provide recipes and packages for the workflows and analyses that flow through the core here at Brown University. Rather than duplicating efforts we actually leverage the bioconda recipes quite heavily and our plan is to contribute back to bioconda those recipes that don't yet exist or need fixing( Like i did so for the `subread` package). In fact, we are also encouraging our computational biologist here to submit their software packages both as independent packages and as bioconda recipes.
      Hope this clarifies our efforts and please don't hesitate to reach out if you have any thoughts and suggestions.
     Cheers
      Ashok

**Comment by johanneskoester** [comment]
Hi Ashok!
That is great to hear!
Thanks for the clarification!
